source: site
paths:
  uploads: uploads
  static: ''
  collections:
  data: _data
  layouts: layouts
  includes: layouts
collections_config:
  pages:
    path: pages
    icon: description
    url: '{permalink}'
    disable_url: false
    description: ''
    _enabled_editors:
      - visual
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/page.html
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  documentation:
    path: documentation
    icon: library_books
    url: /documentation/[slug]/
    disable_url: false
    description: ''
    _enabled_editors:
      - content
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/documentation.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  fleet:
    path: fleet
    icon: airport_shuttle
    url: /fleet/[slug]/
    disable_url: false
    description: ''
    _enabled_editors:
      - visual
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/fleet.html
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  events:
    path: events
    glob:
    name:
    singular_name:
    icon: calendar_month
    url: /events/[slug]/
    disable_url: false
    documentation:
    description: ''
    preview:
    sort:
    sort_options:
    _editables:
    _enabled_editors:
      - content
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    new_preview_url:
    schemas:
      default:
        path: site/schemas/event.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name:
        icon: notes
        preview:
        _editables:
        _enabled_editors:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
    schema_key:
  blog:
    path: blog
    icon: article
    disable_url: false
    description: ''
    preview:
      metadata:
        - text:
            - key: tags
          icon: newspaper
    _enabled_editors:
      - content
      - visual
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: Blog Post
        icon: notes
  data:
    path: _data
    icon: data_object
    disable_url: false
    description: ''
    _enabled_editors:
      - data
    disable_add: true
    disable_add_folder: true
    disable_file_actions: false
collection_groups:
  - heading: Pages
    collections:
      - pages
      - fleet
      - events
      - documentation
  - heading: Blogging
    collections:
      - blog
  - heading: Site Settings
    collections:
      - data
_inputs:
  date:
    type: date
    instance_value: NOW
    cascade: true
  uuid:
    type: auto
    instance_value: UUID
    hidden: true
    cascade: true
  permalink:
    options:
      pattern: ^[\/].*[\/]$|^\/$
      pattern_message: Permalink must start and end with a forward slash.
    cascade: true
  main_column:
    type: markdown
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      blockquote: true
      bold: true
      bulletedlist: true
      center: align-center
      code: true
      expandable: false
      format: p h1 h2 h3 h4 pre
      height: 1400
      horizontalrule: true
      image: true
      image_size_attributes: true
      italic: true
      justify: align-justify
      left: align-left
      link: true
      numberedlist: true
      paths:
        uploads: uploads/content
      redo: true
      removeformat: true
      resize_style: contain
      right: align-right
      strike: true
      styles: /css/editor.css
      subscript: true
      superscript: true
      table: true
      undo: true
      width: 1200
    cascade: true
  left_column:
    type: markdown
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      blockquote: true
      bold: true
      bulletedlist: true
      center: align-center
      code: true
      expandable: false
      format: p h1 h2 h3 h4 pre
      height: 1400
      horizontalrule: true
      image: true
      image_size_attributes: true
      italic: true
      justify: align-justify
      left: align-left
      link: true
      numberedlist: true
      paths:
        uploads: uploads/content
      redo: true
      removeformat: true
      resize_style: contain
      right: align-right
      strike: true
      styles: /css/editor.css
      subscript: true
      superscript: true
      table: true
      undo: true
      width: 1200
    cascade: true
  right_column:
    type: markdown
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      blockquote: true
      bold: true
      bulletedlist: true
      center: align-center
      code: true
      expandable: false
      format: p h1 h2 h3 h4 pre
      height: 1400
      horizontalrule: true
      image: true
      image_size_attributes: true
      italic: true
      justify: align-justify
      left: align-left
      link: true
      numberedlist: true
      paths:
        uploads: uploads/content
      redo: true
      removeformat: true
      resize_style: contain
      right: align-right
      strike: true
      styles: /css/editor.css
      subscript: true
      superscript: true
      table: true
      undo: true
      width: 1200
    cascade: true
  gallery_image:
    type: image
    options:
      paths:
        uploads: uploads/gallery
      resize_style: contain
      width: 1800
      height: 1800
      expandable: false
    label: Gallery Image
    cascade: true
  blog_feature_image:
    type: image
    options:
      paths:
        uploads: uploads/blog
      resize_style: contain
      width: 1200
      height: 1400
      expandable: false
      required: true
      required_message: An image is required.
    label: Featured Image
    comment: Defaults to the image set in the Site SEO data file.
    cascade: true
  meta_image:
    type: image
    options:
      paths:
        uploads: uploads/meta
      resize_style: contain
      width: 1200
      height: 1400
      expandable: false
    label: Meta Image
    comment: >-
      If empty, defaults to the featured image (if a blog post) otherwise to the
      image set in the Site SEO data file.
    cascade: true
  team_image:
    type: image
    options:
      paths:
        uploads: uploads/team
      resize_style: contain
      width: 800
      height: 1000
      expandable: false
    label: Team Member Image
    cascade: true
  slider_image:
    type: image
    options:
      paths:
        uploads: uploads/slider
      resize_style: contain
      width: 1000
      height: 1200
      expandable: false
    label: Slider Image
    cascade: true
  feature_image:
    type: image
    options:
      paths:
        uploads: uploads/feature
      resize_style: contain
      width: 1200
      height: 1000
      expandable: false
    label: Feature Image
    cascade: true
  event_summary_image:
    type: image
    options:
      paths:
        uploads: uploads/events
      resize_style: contain
      width: 1800
      height: 1800
      expandable: false
    label: Event Summary Image
    cascade: true
  multi_column_max_image_width:
    comment: >-
      Hidden. Used with srcset on the image value like 100vw, 50vw, 600px to
      restrict sizing.
    hidden: true
    cascade: true
  image_quality:
    type: number
    options:
      min: 60
      max: 100
      step: 1
    comment: >-
      Enter a value 60 to 100 (Default is 90). Applies to images on production
      sites only.
    cascade: true
  image_aspect_ratio:
    type: select
    options:
      allow_empty: false
      values:
        '1': '1:1'
        '2': '2:1'
        '3': '3:1'
        '1.25': '5:4'
        '1.33': '4:3'
        '1.5': '3:2'
        '1.66': '5:3'
        '1.77': '16:9'
        '0.8': '4:5'
        '0.75': '3:4'
        '0.66': '2:3'
        '0.6': '3:5'
        auto: Auto
    cascade: true
  focal_point:
    type: select
    options:
      allow_empty: false
      values:
        center center: Center Center
        center top: Center Top
        center bottom: Center Bottom
        left top: Left Top
        left center: Left Center
        left bottom: Left Bottom
        right top: Right Top
        right center: Right Center
        right bottom: Right Bottom
    cascade: true
  embed_aspect_ratio:
    type: select
    options:
      allow_empty: false
      values:
        none: None
        ratio-1-1: Square
        ratio-5-4: '5:4'
        ratio-4-3: '4:3'
        ratio-16-9: '16:9'
        ratio-2-1: '2:1'
        ratio-3-1: '3:1'
        ratio-4-5: '4:5'
        ratio-3-4: '3:4'
        ratio-2-3: '2:3'
        ratio-3-5: '3:5'
        ratio-9-16: 9:16 (FB Reels)
    cascade: true
  component_palette:
    type: select
    options:
      allow_empty: true
      values:
        lightest: Lightest
        lighter: Lighter
        light: Light
        dark: Dark
        darker: Darker
        darkest: Darkest
        alternate-1: Alternate 1
        alternate-2: Alternate 2
        alternate-3: Alternate 3
    cascade: true
    allow_empty: false
  component_palette_secondary:
    type: select
    options:
      allow_empty: true
      values:
        lightest: Lightest
        lighter: Lighter
        light: Light
        dark: Dark
        darker: Darker
        darkest: Darkest
        alternate-1: Alternate 1
        alternate-2: Alternate 2
        alternate-3: Alternate 3
    cascade: true
    allow_empty: false
  title_size:
    type: select
    options:
      allow_empty: true
      values:
        h1: H1
        h2: H2
        h3: H3
    cascade: true
  content_alignment:
    type: select
    options:
      allow_empty: true
      values:
        left: Left
        centered: Centered
        right: Right
    cascade: true
  content_padding_top:
    type: number
    options:
      min: 0
      max: 7
      step: 1
    cascade: true
    allow_empty: false
  content_padding_bottom:
    type: number
    options:
      min: 0
      max: 7
      step: 1
    cascade: true
    allow_empty: false
  pagination.data:
    type: auto
    hidden: true
    cascade: true
  pagination.alias:
    type: auto
    hidden: true
    cascade: true
  social:
    type: auto
    options:
      structures: _structures.social
      preview:
        icon: link
    cascade: true
  links:
    type: auto
    options:
      structures: _structures.links
      preview:
        icon: link
    cascade: true
  sections:
    type: auto
    options:
      structures: _structures.sections
      preview:
        icon: link
    cascade: true
  items:
    type: auto
    options:
      preview:
        icon: link
    cascade: true
  address:
    type: textarea
    cascade: true
  hours:
    type: textarea
    cascade: true
  use_fetch:
    type: auto
    comment: Check if want to have AJAX page transitions.
    cascade: true
  base_url:
    type: auto
    comment: Use production site base URL (leave off the trailing forward slash).
    cascade: true
  site_title:
    type: auto
    comment: Used for SEO
    cascade: true
  site_description:
    type: auto
    comment: Default meta description for SEO
    cascade: true
  site_logo:
    type: image
    options:
      paths:
        uploads: uploads/theme
      resize_style: contain
      width: 300
      height: 300
      expandable: false
    cascade: true
  site_image:
    type: image
    options:
      paths:
        uploads: uploads/defaults
      resize_style: contain
      width: 1600
      height: 1600
      expandable: false
    comment: Default image for SEO
    cascade: true
  twitter_image:
    type: image
    options:
      paths:
        uploads: uploads/defaults
      resize_style: contain
      width: 1600
      height: 1600
      expandable: false
    comment: Default image for SEO
    cascade: true
  twitter_site:
    type: twitter
    label: Twitter Username/Handle
    comment: Default for page SEO (for example @happymarketer)
    cascade: true
  placeholder_image:
    type: image
    comment: Used as default image until replaced
    cascade: true
  meta_title:
    type: auto
    comment: If empty, defaults to the title of the page
    cascade: true
  meta_description:
    type: auto
    comment: >-
      If empty, defaults to the excerpt (if a blog post) otherwise to the
      description set in the Site SEO data file
    cascade: true
  canonical_url:
    type: auto
    comment: If empty, defaults to the page URL
    cascade: true
  open_graph_type:
    type: select
    options:
      allow_empty: true
      values:
        - website
        - article
        - profile
    cascade: true
  author_twitter_handle:
    type: twitter
    comment: Defaults to the twitter site value set in the Site SEO data file
    cascade: true
  no_index:
    type: checkbox
    comment: >-
      When selected this removes the page from your sitemap and adds the noindex
      robots meta tag
    cascade: true
  enable_dropdown:
    type: switch
    comment: Enables dropdown of sub-navigation items (if present) on the main navbar.
    cascade: true
  sub_navigation_group_title:
    comment: >-
      Used in the sub-navigation components to know which sub navigation items
      to display.
    cascade: true
  sub_navigation:
    type: array
    options:
      structures: _structures.sub_navigation
    label: Sub Navigation Items
    cascade: true
  navigation_group:
    type: select
    options:
      allow_empty: true
      values: data.nav.items[*].sub_navigation_group_title
    comment: >-
      Pulled from on any sub-navigation group titles added in the main nav file
      of the data folder ('_data/nav.json').
    cascade: true
  excerpt:
    type: textarea
    comment: Short summary of page (e.g. first one or two sentences)
    cascade: true
  fleet_category:
    type: select
    options:
      allow_empty: true
      values: data.fleet-categories.category
    comment: Choose fleet category this item belongs to (for filtering).
    cascade: true
  tags:
    type: multiselect
    options:
      allow_empty: true
      values: data.blog-tags
      value_key: title
      preview:
        text:
          - key: title
      empty_type: array
    cascade: true
  layout:
    type: auto
    hidden: true
    cascade: true
  eleventyExcludeFromCollections:
    type: auto
    hidden: true
    cascade: true
_structures:
  content_blocks:
    style: modal
  sub_navigation:
    style: select
    values:
      value:
        text:
        link:
  social:
    style: select
    values:
      value:
        link:
        icon:
        title:
  sections:
    style: select
    values:
      value:
        title:
        links:
  links:
    style: select
    values:
      value:
        text:
        link:
  photos:
    style: select
    values:
      - label: Gallery Image
        image_key: gallery_image
        icon: add_a_photo
        value:
          gallery_image:
          title:
  embed_code:
    style: select
    values:
      - icon: play_circle
        label: Embed Code
        value:
          code_block:
          embed_aspect_ratio:
_editables:
  content:
    blockquote: true
    bold: true
    format: p h1 h2 h3 h4 pre
    italic: true
    link: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    styles: /css/editor.css
    left: align-left
    center: align-center
    right: align-right
    justify: align-justify
    bulletedlist: true
    numberedlist: true
    indent: true
    outdent: true
    join_above: true
    join_below: true
    image_size_attributes: true
    width: 1200
    height: 1400
    resize_style: contain
    expandable: false
    allowed_sources:
      - site-files
    code: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    undo: true
    redo: true
    removeformat: true
    paths:
      uploads: uploads/content
    allow_custom_markup: false
data_config:
  blog-tags:
    path: _data/blog-tags.json
  contact:
    path: _data/contact.json
  fleet-categories:
    path: _data/fleet-categories.json
  nav:
    path: _data/nav.json
  nav-docs:
    path: _data/nav-docs.json
  sub-nav:
    path: _data/sub-nav.json
  footer:
    path: _data/footer.json
  site:
    path: _data/site.json
  icon-sets:
    path: _data/icon-sets.json
timezone: Pacific/Auckland
